### ISSUE TITLE
b1 & b2 variables

### ISSUE THREAD

**Issue by alashkari** [y0ast/Variational-Autoencoder#13]
Hi,

I'm a little new to the concept of VAE. Would you please give me a hint what b1 and b2 variables are?
Generally, how can we tune this AE for different types of datasets?

Thanks.

**Comment by y0ast** [comment]
Hi, they're beta 1 and beta 2 from the adam paper: https://arxiv.org/pdf/1412.6980.pdf

Generally leaving them to default is just fine :)
