### ISSUE TITLE
clarification rather than issue

### ISSUE THREAD

**Issue by nabsabraham** [y0ast/Variational-Autoencoder#15]
thanks for your implementation! In your model right now, upon inference the model is still taking random sample from a unit normal and reparametrizing it. Shouldn't the model inference be non-stochastic? Please correct me if I'm wrong as I'm just getting the hang of vaes.

**Comment by y0ast** [comment]
Hey! Thanks for your question.

That's actually a point of contention. I follow Durk's guidance and make it stochastic. Here he is fixing it in the PyTorch example https://github.com/pytorch/examples/pull/419 (I can highly recommend PyTorch over this implementation btw!).
