### ISSUE TITLE
About the  positive L(theta ,phy)

### ISSUE THREAD

**Issue by ysjakking** [y0ast/Variational-Autoencoder#7]
When I run the continue mode which models X using gaussion, after some iterations .I get positive L(theta ,phy)=E_z ( -KL + log p(x|z) ). 
Since both "-KL"  and "log p(x|z)"  are negative values ,I wonder what happened.
In more detail, I find positive  log p(x|z) during debugging , which indicate that  p(x|z)>1 .  I wonder if the code 
" logpxz = (-(0.5 \* np.log(2 \* np.pi) + 0.5 \* log_sigma_decoder) - 0.5 \* ((x - reconstructed_x)**2 / T.exp(log_sigma_decoder))).sum(axis=1)"  is right.

**Comment by y0ast** [comment]
See the bottom graphs of figure 2 in the original paper: http://arxiv.org/pdf/1312.6114v10.pdf

Those are positive values too :)
